-- MySQL Script generated by MySQL Workbench
-- jue 19 nov 2020 17:25:50 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_catastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_catastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_catastro` DEFAULT CHARACTER SET utf8 ;
USE `mydb_catastro` ;

-- -----------------------------------------------------
-- Table `mydb_catastro`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_catastro`.`Zona` (
  `Localidad` VARCHAR(60) NOT NULL,
  `Concejal` VARCHAR(60) NOT NULL,
  `Municipio` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_catastro`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_catastro`.`Bloque` (
  `Número` INT NOT NULL,
  `Calle` VARCHAR(60) NOT NULL,
  `Año de construción` INT NOT NULL,
  `Localidad` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Número`, `Calle`),
  CONSTRAINT `Localidad`
    FOREIGN KEY (`Localidad`)
    REFERENCES `mydb_catastro`.`Zona` (`Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_catastro`.`Vivienda Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_catastro`.`Vivienda Unifamiliar` (
  `Número` INT NOT NULL,
  `Calle` VARCHAR(60) NOT NULL,
  `Año de construción` INT NOT NULL,
  `Localidad` VARCHAR(60) NOT NULL,
  `Número de habitaciones` INT NOT NULL,
  PRIMARY KEY (`Número`, `Calle`),
  CONSTRAINT `Localida`
    FOREIGN KEY (`Localidad`)
    REFERENCES `mydb_catastro`.`Zona` (`Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_catastro`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_catastro`.`Piso` (
  `Planta` INT NOT NULL,
  `Letra` VARCHAR(2) NOT NULL,
  `Número de habitaciones` INT NOT NULL,
  `Número` INT NOT NULL,
  `Calle` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Planta`, `Letra`, `Número`, `Calle`),
  CONSTRAINT `Número`
    FOREIGN KEY (`Número`)
    REFERENCES `mydb_catastro`.`Bloque` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_catastro`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_catastro`.`Persona` (
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Fecha de nacimiento` VARCHAR(45) NOT NULL,
  `Vivienda Unifamiliar_Número` INT NOT NULL,
  `Vivienda Unifamiliar_Calle` VARCHAR(60) NOT NULL,
  `Piso_Planta` INT NOT NULL,
  `Piso_Letra` VARCHAR(2) NOT NULL,
  `Piso_Número` INT NOT NULL,
  `Piso_Calle` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`DNI`, `Vivienda Unifamiliar_Número`, `Vivienda Unifamiliar_Calle`, `Piso_Planta`, `Piso_Letra`, `Piso_Número`, `Piso_Calle`),
  CONSTRAINT `fk_Persona_Vivienda Unifamiliar1`
    FOREIGN KEY (`Vivienda Unifamiliar_Número` , `Vivienda Unifamiliar_Calle`)
    REFERENCES `mydb_catastro`.`Vivienda Unifamiliar` (`Número` , `Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Piso1`
    FOREIGN KEY (`Piso_Planta` , `Piso_Letra` , `Piso_Número` , `Piso_Calle`)
    REFERENCES `mydb_catastro`.`Piso` (`Planta` , `Letra` , `Número` , `Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Una persona no vive en dos lugares
-- -----------------------------------------------------

DELIMITER // 
USE `mydb_catastro`;

CREATE DEFINER = `kabir`@`ull.es` TRIGGER `mydb_catastro`.`Persona_una_vivienda` BEFORE INSERT ON `Persona` FOR EACH ROW
BEGIN
	IF ((NEW.Piso_Letra IS NOT NULL) AND (NEW.Piso_Planta IS NOT NULL) AND (Piso_Calle IS NOT NULL) AND (Piso_Numero IS NOT NULL) AND 	  		(Vivienda Unifamiliar_Número IS NOT NULL) AND (Vivienda Unifamiliar_Calle IS NOT NULL)) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Una persona no puede estar alojada en dos viviendas';
	END IF;
END
//
DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
